name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  # Corrigido para rodar de 12 em 12 horas corretamente
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Snake Animation
      - uses: Platane/snk@v3  # Atualizado para versão mais recente
        id: snake-gif
        with:
          github_user_name: Lipe55
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  
